name: prcheck
on: [pull_request]
jobs:
  prcheck:
    runs-on: [ubuntu-latest]
    steps:
      - name: echo headlabel
        run: |
          echo ${{ github.event.pull_request.head.label }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: check fork secrets
        run: |
          echo $FORK
        env:
          FORK: ${{ secrets.fork }}
      - name: check parent secrets
        run: |
          echo $PARENT
        env:
          PARENT: ${{ secrets.parent }}
