name: prcheck
on: [pull_request]
jobs:
  prcheck:
    runs-on: [ubuntu-latest]
    steps:
      - name: echo actor
        run: |
          echo github.actor
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
