name: prcheck
on: [pull_request]
jobs:
  prcheck:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout 2nd
        uses: actions/checkout@v2
        with:
          repository: weide-zhou/ticket19
          token: ${{ secrets.PARENT }}
          path: ticket19
          persist-credentials: false
      - name: checkout 1st
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          clean: false
      - name: touch file
        run: |
          touch filetest1.txt
      - name: Commit newly trained model
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "Model retraining" -a
      - name: Push newly trained model
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.PARENT }}
