name: prcheck
on: [pull_request]
jobs:
  prcheck:
    if: startsWith(github.actor, 'weide-zhou')
 #   if: startsWith(github.event.pull_request.head.label, 'weide-zhou:')
    runs-on: [ubuntu-latest]
    steps:
      - name: echo headlabel
        run: |
          echo ${{ github.event.pull_request.head.label }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
